// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShop.Data;

#nullable disable

namespace Shop.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231226103315_initalMigration")]
    partial class initalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Shop.Models.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Shop.Models.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nummber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Shop.Models.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Shop.Models.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("orderHeaders");
                });

            modelBuilder.Entity("Shop.Models.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Shop.Models.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("WebShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Bánh Sự Kiện"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Bánh kem tươi hoa quả"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Bánh sinh nhật bé trai,bé gái"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Bánh sinh nhật kem bơ"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Bánh sinh nhật nam, nữ"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Bánh Tiramisu"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Bánh kem số & chữ"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Bánh bông lan trứng muối"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Bánh tạo hình fondant"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Bánh Mousse  "
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Bánh sinh nhật  "
                        });
                });

            modelBuilder.Entity("WebShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Bánh sự kiện là 1 loại bánh để trang trí  ",
                            Price = 90000.0,
                            Size = "S",
                            Title = "Bánh sự kiện - Trang trí hoa quả"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Bánh kem tươi hoa quả là sự kết hợp giữa kem whipping và hoa quả tươi tạo nên 1 sự kết hợp rất hài hòa. Bánh kem tươi qua quả phù hợp cho người lớn  ",
                            Price = 35600.0,
                            Size = "S",
                            Title = "Bánh kem tươi hoa quả - Trang trí dâu tây"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Bánh kem tươi hoa quả là sự kết hợp giữa kem whipping và hoa quả tươi tạo nên 1 sự kết hợp rất hài hòa. Bánh kem tươi qua quả phù hợp cho người lớn  ",
                            Price = 39500.0,
                            Size = "S",
                            Title = "Bánh kem tươi hoa quả - Full hoa quả"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Bánh kem tươi hoa quả là sự kết hợp giữa kem whipping và hoa quả tươi tạo nên 1 sự kết hợp rất hài hòa. Bánh kem tươi qua quả phù hợp cho người lớn  ",
                            Price = 42500.0,
                            Size = "M",
                            Title = "Bánh kem tươi hoa quả - Full hoa quả"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Bánh sinh nhật bé trai được tạo hình phù hợp cho các bé trai. ",
                            Price = 36500.0,
                            Size = "S",
                            Title = "Bánh sinh nhật bé trai"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Bánh sinh nhật bé trai được tạo hình phù hợp cho các bé trai",
                            Price = 39500.0,
                            Size = "M",
                            Title = "Bánh sinh nhật bé trai"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Bánh sinh nhật bé gái được tạo hình phù hợp cho các bé gái.",
                            Price = 36500.0,
                            Size = "S",
                            Title = "Bánh sinh nhật bé gái"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Bánh sinh nhật bé gái được tạo hình phù hợp cho các bé gái.",
                            Price = 39500.0,
                            Size = "M",
                            Title = "Bánh sinh nhật bé gái - Trang trí gấu dâu"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Bánh sinh nhật kem bơ. Đây là 1 dòng kem bơ ăn ngậy hơi béo, với dòng kem bơ chúng ta có thể để được ở ngoài lâu. Dòng kem này khá kén người ăn ",
                            Price = 395000.0,
                            Size = "S",
                            Title = "Bánh sinh nhật kem bơ"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Bánh sinh nhật kem bơ. Đây là 1 dòng kem bơ ăn ngậy hơi béo, với dòng kem bơ chúng ta có thể để được ở ngoài lâu. Dòng kem này khá kén người ăn ",
                            Price = 425000.0,
                            Size = "M",
                            Title = "Bánh sinh nhật kem bơ - Tạo hình con mèo"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Description = "Bánh sinh nhật bé gái được tạo hình phù hợp cho các bạn nam ",
                            Price = 365000.0,
                            Size = "S",
                            Title = "Bánh sinh nhật nam - Bánh vẽ hình chibi"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Description = "Bánh sinh nhật bé gái được tạo hình phù hợp cho các bạn nam ",
                            Price = 425000.0,
                            Size = "M",
                            Title = "Bánh sinh nhật nam - Bánh trang trí hình nộm"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            Description = "Bánh Tiramisu là 1 loại bánh có nguồn gốc từ ý, chiếc bánh này được làm thành 1 ổ bánh to và trang trí hấp dẫn thành tâm điểm của 1 bữa tiệc sinh nhật. Nhưng phần cốt bánh mềm xốp được thấm đẫm với hương cà phê và rượu rum, cùng với phần kem được phết ở giữa béo ngậy",
                            Price = 365000.0,
                            Size = "S",
                            Title = "Bánh Tiramisu - Mix vị"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            Description = "Bánh Tiramisu là 1 loại bánh có nguồn gốc từ ý, chiếc bánh này được làm thành 1 ổ bánh to và trang trí hấp dẫn thành tâm điểm của 1 bữa tiệc sinh nhật. Nhưng phần cốt bánh mềm xốp được thấm đẫm với hương cà phê và rượu rum, cùng với phần kem được phết ở giữa béo ngậy",
                            Price = 365000.0,
                            Size = "S",
                            Title = "Bánh Tiramisu - Vị cacao, Trang trí hoa quả"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 7,
                            Description = "Bánh kem số & chữ là bánh được cắt thành hình chữ hoặc số theo yêu cầu của khách hàng. Bánh được làm bằng kem whippng và có mứt và hoa quả làm nhân ở giữa",
                            Price = 395000.0,
                            Size = "S",
                            Title = "Bánh kem số & chữ - Tạo hình số 7"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 7,
                            Description = "Bánh kem số & chữ là bánh được cắt thành hình chữ hoặc số theo yêu cầu của khách hàng. Bánh được làm bằng kem whippng và có mứt và hoa quả làm nhân ở giữa",
                            Price = 495000.0,
                            Size = "M",
                            Title = "Bánh kem số & chữ - Cắt hình chữ A "
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 8,
                            Description = "Bánh bông lan trứng muối là sự hòa quyện giữa vị mặn của trứng với vị ngọt dịu của vỏ bánh bông lan",
                            Price = 295000.0,
                            Size = "S",
                            Title = "Bánh bông lan trứng muối "
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            Description = "Bánh tạo hình fondant được làm từ chất liệu fondant nặn thành những hình thù đáng yêu ngộ nghĩng",
                            Price = 395000.0,
                            Size = "S",
                            Title = "Bánh tạo hình fondant - Bánh tạo hình cốc bia "
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 9,
                            Description = "Bánh tạo hình fondant được làm từ chất liệu fondant nặn thành những hình thù đáng yêu ngộ nghĩng",
                            Price = 495000.0,
                            Size = "M",
                            Title = "Bánh tạo hình fondant - Bánh trang trí tạo hình con thỏ "
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 10,
                            Description = "Bánh Mousse là 1 loại bánh lạnh trở nên thịnh hành trong những năm trở lại đây, chiếc bánh mousse có ưu điểm dễ làm, nhanh gọn và không cần sử dụng đến lò nướng. Đây được xem là lựa chọn hàng đầu cho những người mới làm bánh hay chưa thạo làm bánh sinh nhật. Bánh Mousse là họ hàng của dòng bánh lạnh nên vị man mát, béo ngậy của kem tươi hòa cùng với những hương bị đã tạo nen sự độc đáo",
                            Price = 495000.0,
                            Size = "M",
                            Title = "Bánh Mousse - Vị sữa chua trang trí nho sữa "
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 10,
                            Description = "Bánh Mousse là 1 loại bánh lạnh trở nên thịnh hành trong những năm trở lại đây, chiếc bánh mousse có ưu điểm dễ làm, nhanh gọn và không cần sử dụng đến lò nướng. Đây được xem là lựa chọn hàng đầu cho những người mới làm bánh hay chưa thạo làm bánh sinh nhật. Bánh Mousse là họ hàng của dòng bánh lạnh nên vị man mát, béo ngậy của kem tươi hòa cùng với những hương bị đã tạo nen sự độc đáo",
                            Price = 535000.0,
                            Size = "L",
                            Title = "Bánh Mousse - Vị xoài trang trí bằng các miếng xoài "
                        });
                });

            modelBuilder.Entity("Shop.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shop.Models.Models.OrderDetail", b =>
                {
                    b.HasOne("Shop.Models.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Models.Models.OrderHeader", b =>
                {
                    b.HasOne("Shop.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Shop.Models.Models.ProductImage", b =>
                {
                    b.HasOne("WebShop.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Models.Models.ShoppingCart", b =>
                {
                    b.HasOne("Shop.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebShop.Models.Product", b =>
                {
                    b.HasOne("WebShop.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop.Models.ApplicationUser", b =>
                {
                    b.HasOne("Shop.Models.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WebShop.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
